PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS Students (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName  TEXT NOT NULL,
  Email     TEXT NOT NULL,
  EnrollmentDate TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Courses (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Title  TEXT NOT NULL,
  Credits INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Enrollments (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  StudentId INTEGER NOT NULL,
  CourseId  INTEGER NOT NULL,
  Grade     TEXT NULL,
  FOREIGN KEY (StudentId) REFERENCES Students(Id) ON DELETE CASCADE,
  FOREIGN KEY (CourseId)  REFERENCES Courses(Id)  ON DELETE CASCADE
);
